# Generated by Django 4.0.3 on 2022-03-27 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collection Name*:')),
                ('twitterurl', models.CharField(blank=True, help_text='(followers < 500 ? ‘rejected’ : ‘pass’)', max_length=255, null=True, verbose_name='Twitter url*:')),
                ('discordid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discord ID*:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*:')),
                ('stage', models.IntegerField(choices=[(1, 'Stage 1: I just have started'), (2, 'Stage 2: I can generate multiple images and attributes'), (3, 'Stage 3: I have all the images and attributes for each.')], default=1, verbose_name='How will you describe your current stage of artwork*?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Describe your project and its long term vision*:')),
                ('artworkdata', models.FileField(upload_to='artwork', validators=[django.core.validators.FileExtensionValidator(['json', 'png'])], verbose_name='Send a sample of your artwork (png + json format):')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
